name: Update README with GitHub Stats
on: [push, schedule]  # Ejecutar al hacer push y según cron.
schedule:
  - cron: "0 0 * * *"  # Ejecutar automáticamente cada día a la medianoche.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Utiliza la acción para clonar el repositorio.

      - name: Set up Node.js  # Configura Node.js (similar a tu ejemplo).
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Versión de Node.js.

      - run: echo "TOKEN_STATS=${{ secrets.TOKEN_STATS }}" >> $GITHUB_ENV  # Paso para configurar el token.

      - name: Generate GitHub Stats
        run: |
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&count_private=true&include_all_commits=true&token=${{ secrets.TOKEN_STATS }})" > stats.md

      - name: Update README
        run: |
          sed -i '/^<!--START_SECTION:github-stats-->/r stats.md' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest GitHub stats"
          git push